Hello Microverse Pull Request
MarkYegon7/Microverse-Hello-World pull request #1
Opened 2023-02-15 08:58 UTC by MarkYegon7

2023-02-15 10:24 UTC, topeogunleye requested changes
Hi @MarkYegon7, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![Try-Again](https://user-images.githubusercontent.com/52934128/180646051-aed7efa6-6d15-4853-9962-73186e366f2c.gif)

> ## (Highlights) Good Points: 💪 
> * Good commit messages. :heavy_check_mark:
> * No linter errors. :heavy_check_mark:
> * Followed Github flow :heavy_check_mark:
> * Professional README file. :heavy_check_mark:

## Required Changes ♻️
In the case of README, kindly make use the  [Microverse README](https://github.com/microverseinc/readme-template) and also remember to personalize the template to have your project info as seen in the example  of a professional README template below, as it's a project requirement. 
  - Kindly add all sections from the Microverse README.
  - The only optional section from the README file is faq.

| professional Readme  | Your Readme that is not professional |
| ------------- | ------------- |
|  ![Recording 2023-02-14 at 12 52 20 (5)](https://user-images.githubusercontent.com/83360636/218715072-2b2d3a49-8219-4939-b350-45cc950f7f7a.gif)	  | ![README md - Microverse-Hello-World  WSL_ Ubuntu  - Visual Studio Code 2023-02-15 11-13-07](https://user-images.githubusercontent.com/52934128/218999655-287143f1-f4c4-4fad-80b4-9173283086ce.gif) |

- [ ] Please kindly add a more descriptive PR title and description as seen in the demo below:
![pull_request_desc](https://user-images.githubusercontent.com/52934128/177452738-0610c008-a53a-454e-8aac-635cb4ed812c.gif)

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- x
- y
- z

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-17 17:02 UTC, souad988 requested changes
Hi @MarkYegon7 , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
✔Linters setup correctly and pass all checks. 

 ## Required Changes ♻️
_one last think before approving your work, please update your PR title to something that describes better this feature exp: Setup linters/ Add hello world html 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-17 17:02 UTC, souad988 commented on README.md
> +
[ OPTIONAL ] kindly remove all default text that comes under each section as it added to guide you but should be removed after customizing each section.

2023-02-17 17:44 UTC, Tadesse-Alemayehu approved these changes
### Hi @MarkYegon7 

### I'm Tadesse Alemayehu your reviewer for this PR. :hand: 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![giphy (1)](https://user-images.githubusercontent.com/69077061/212969210-69f495ba-f2fb-4559-a222-d1507310d6fb.gif)

## Highlights
 - [ ] Good job making the changes requested by the previous code reviewer. ✅

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-17 17:44 UTC, Tadesse-Alemayehu commented on README.md
> +
- [Optional] Please consider removing non-important contents from your readme, The template is designed by Microverse for us all to use to document our projects professionally and has it filled with content related to each project we may be working on. currently, I can see you have not removed the guiding contents  which start with `>` and `directions set by Microverser`

2023-02-17 17:45 UTC, merged